version: "3"
services:
  postgres:
    image: postgres:16
    working_dir: /app
    volumes:
      - ${POSTGRES_VOLUMES}:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env

